### ISSUE TITLE
Fetch fails when debugfunction set

### ISSUE THREAD

**Issue by hadley** [jeroenooms/curl#26]
and it breaks the handle

```R
library(curl)
h <- new_handle(verbose = TRUE, debugfunction = function(type, msg) NULL)
curl_fetch_memory("http://had.co.nz", handle = h)
curl_fetch_memory("http://had.co.nz", handle = h)
```

**Comment by jeroenooms** [comment]
Fixed @ https://github.com/jeroenooms/curl/commit/0911193a6fbc9fe19d6e57484ec4c6074d1ce545. You cannot assume response data are strings, they body or ssl part might contain binary data. R doesn't like that. 

The debug function is now called with raw vectors instead of strings. If you want we can add some high level logic that will automatically convert the raw vec to a string when `type < 3` or so.

**Comment by hadley** [comment]
Oh that makes sense - thanks!
