### ISSUE TITLE
anyNA requires R >= 3.1.0

### ISSUE THREAD

**Issue by mjkallen** [jeroenooms/curl#34]
@jeroenooms you added the `anyNA()` function in commit ff76a61808d7faddb5b35a1a63202293c5a6743b but you don't require R >= 3.1.0 in the DESCRIPTION file. I get an error that `anyNA()` is not found when using R < 3.1.0. Either you do the sensible thing and just use `any(is.na(keys))` or you bump the minimum required version of R to 3.1.0.

**Comment by jeroenooms** [comment]
Fixed @ https://github.com/jeroenooms/curl/commit/5e380375a8e9e69d7c36a91bf3a1a651d1e6a82b. Why are you using a deprecated version of R?

**Comment by jeroenooms** [comment]
If you find any other compatibility problems with pre `r-oldrel` versions just send a PR :)

**Comment by mjkallen** [comment]
Thanks for the fix and, for good order,

1. I wouldn't consider any 3.x version of R as deprecated, even if it's pre `r-oldrel` and if you do want to consider these deprecated then you should just depend on R (>=3.1.3) in the DESCRIPTION file,
2. using `anyNA()` is unnecessary as `keys` is not a huge vector on which my computer is going to choke,
3. when people started using that other useless function `paste0` they correctly bumped their dependency to R (>=2.15.0) so their is a precedent for these cases.

**Comment by jeroenooms** [comment]
I don't mind at all, but it is difficult to detect these kind of problems because the CRAN testing suite only tests on `r-oldrel`, `r-release` and `r-devel`. I'm sure there are other things in the package that require at least 3.0 or so, but it would be silly to check when each function was introduced. Afaik the convention is to only declare a minimum version if it requires something more recent than `r-oldrel` at the time of the release of the package.

You didn't answer the question by the way :) Does renjin target the 3.0 reference implementation?

**Comment by mjkallen** [comment]
Renjin is currently a fork of R 2.14.2, but I was using R 3.0.2 in a completely different context when I hit this error.
